use crate::error::AppError;
use crate::provision::commands::ssh_root_async;
use std::path::Path;

/// Configure vim and git globally.
/// System tool packages already installed by cloud-init.
/// Translated from openclaw-ansible system-tools.yml + vimrc.j2.
pub async fn provision(ip: &str, key: &Path) -> Result<(), AppError> {
    // Write global vim configuration
    let vimrc = r##"cat > /etc/vim/vimrc.local << 'VIMEOF'
" Vim Configuration - Generated by ClawMacToDO
" Modern, practical vim setup for development and debugging

" Basic Settings
set nocompatible
filetype plugin indent on
syntax on

" UI Settings
set number
set relativenumber
set ruler
set showcmd
set wildmenu
set showmatch
set cursorline
set laststatus=2
set colorcolumn=80,120

" Search Settings
set incsearch
set hlsearch
set ignorecase
set smartcase

" Indentation
set autoindent
set smartindent
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2

" Performance
set lazyredraw
set ttyfast

" Backups and Undo
set nobackup
set nowritebackup
set noswapfile
set undofile
set undodir=~/.vim/undo
set undolevels=1000
set undoreload=10000

" File Handling
set encoding=utf-8
set fileencoding=utf-8
set autoread
set hidden

" Navigation
set scrolloff=8
set sidescrolloff=8
set mouse=a

" Folding
set foldmethod=indent
set foldlevel=99

" Status Line
set statusline=%F%m%r%h%w%=%y\ [%{&ff}]\ [%{strlen(&fenc)?&fenc:'none'}]\ %l:%c\ %p%%

" Key Mappings
let mapleader = ","
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader><space> :nohlsearch<CR>
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Paste toggle
set pastetoggle=<F2>

" File Type Specific
autocmd FileType python setlocal tabstop=4 shiftwidth=4 softtabstop=4
autocmd FileType javascript,typescript,json setlocal tabstop=2 shiftwidth=2 softtabstop=2
autocmd FileType yaml,yml setlocal tabstop=2 shiftwidth=2 softtabstop=2
autocmd FileType go setlocal tabstop=4 shiftwidth=4 softtabstop=4 noexpandtab
autocmd FileType markdown setlocal wrap linebreak nolist

" Auto-create undo directory
if !isdirectory($HOME."/.vim/undo")
    call mkdir($HOME."/.vim/undo", "p", 0700)
endif

" Colors
set background=dark
if &term =~ "xterm" || &term =~ "screen"
    set t_Co=256
endif

" Highlight trailing whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

" Remember cursor position
autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif
VIMEOF
"##;
    ssh_root_async(ip, key, vimrc).await?;

    // Configure git globally
    let git_cfg = r#"
git config --global init.defaultBranch main && \
git config --global pull.rebase false && \
git config --global core.editor vim && \
git config --global color.ui auto && \
git config --global alias.st status && \
git config --global alias.co checkout && \
git config --global alias.br branch && \
git config --global alias.ci commit && \
git config --global alias.unstage 'reset HEAD --' && \
git config --global alias.last 'log -1 HEAD' && \
git config --global alias.lg 'log --oneline --graph --decorate --all'
"#;
    ssh_root_async(ip, key, git_cfg).await?;

    Ok(())
}
